#!/bin/bash
#
# Notes CouchDB - Development Setup Script
#
# This script sets up Notes for local development:
# - Creates /opt/notes directory structure
# - Creates /opt/notes/.env with dev credentials
# - Checks/creates external network
#
# Usage:
#   bash dev-setup.sh
#
# Requirements:
#   - Docker and Docker Compose installed
#
# Author: Family Budget Team
# Version: 1.0.0
# Date: 2025-11-16
#

set -e  # Exit on error

# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOTES_DIR="/opt/notes"
ENV_FILE="$NOTES_DIR/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

print_message() {
    local color=$1
    shift
    echo -e "${color}$*${NC}"
}

info() {
    print_message "$BLUE" "[INFO] $*"
}

success() {
    print_message "$GREEN" "[SUCCESS] $*"
}

warning() {
    print_message "$YELLOW" "[WARNING] $*"
}

error() {
    print_message "$RED" "[ERROR] $*"
    exit 1
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# =============================================================================
# SETUP FUNCTIONS
# =============================================================================

check_docker() {
    if ! command_exists docker; then
        error "Docker not installed. Please install Docker first:
    https://docs.docker.com/engine/install/"
    fi

    if ! docker ps >/dev/null 2>&1; then
        error "Docker is not running. Please start Docker."
    fi

    success "Docker is running"
}

setup_directories() {
    info "Setting up /opt/notes directory structure..."

    # Check if we need sudo
    if [[ ! -d "/opt/notes" ]]; then
        if [[ -w "/opt" ]]; then
            # Can write to /opt without sudo
            mkdir -p "$NOTES_DIR"/{data,backups,logs}
        else
            # Need sudo
            info "Creating /opt/notes (requires sudo)..."
            sudo mkdir -p "$NOTES_DIR"/{data,backups,logs}
            sudo chown -R "$(whoami):$(whoami)" "$NOTES_DIR"
        fi
    else
        # Directory exists, check if we can write
        if [[ ! -w "$NOTES_DIR" ]]; then
            info "Fixing /opt/notes permissions (requires sudo)..."
            sudo chown -R "$(whoami):$(whoami)" "$NOTES_DIR"
        fi

        # Create subdirectories if missing
        mkdir -p "$NOTES_DIR"/{data,backups,logs}
    fi

    chmod 755 "$NOTES_DIR"
    chmod 755 "$NOTES_DIR"/{data,backups,logs}

    success "Directory structure created"
}

create_dev_env() {
    info "Creating development .env file..."

    if [[ -f "$ENV_FILE" ]]; then
        warning ".env file already exists: $ENV_FILE"
        echo ""
        read -p "Overwrite with dev credentials? (y/N): " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            info "Keeping existing .env file"
            return 0
        fi
    fi

    cat > "$ENV_FILE" << 'EOF'
# =============================================================================
# Notes CouchDB Development Environment
# =============================================================================
# Generated by notes/dev-setup.sh
# INSECURE - FOR DEVELOPMENT ONLY!

# =============================================================================
# CouchDB Credentials
# =============================================================================

COUCHDB_USER=admin
COUCHDB_PASSWORD=dev_password_insecure

# =============================================================================
# Notes Domain Configuration
# =============================================================================

NOTES_DOMAIN=notes.localhost

# =============================================================================
# Data Directories
# =============================================================================

NOTES_DATA_DIR=/opt/notes/data
NOTES_BACKUP_DIR=/opt/notes/backups
NOTES_LOG_DIR=/opt/notes/logs

# =============================================================================
# Network Configuration
# =============================================================================

COUCHDB_PORT=5984
EOF

    chmod 600 "$ENV_FILE"

    success "Development .env created: $ENV_FILE"
    warning "INSECURE CREDENTIALS - Use only for development!"
}

check_or_create_network() {
    info "Checking external network..."

    if docker network ls --format '{{.Name}}' | grep -q '^familybudget_familybudget$'; then
        success "External network 'familybudget_familybudget' exists"
    else
        warning "External network 'familybudget_familybudget' not found"
        echo ""
        read -p "Create network now? (Y/n): " -n 1 -r
        echo ""

        if [[ $REPLY =~ ^[Nn]$ ]]; then
            warning "Network not created. You must create it manually or start Family Budget first."
        else
            info "Creating network 'familybudget_familybudget'..."
            docker network create familybudget_familybudget
            success "Network created"
        fi
    fi
}

copy_local_ini() {
    info "Copying CouchDB configuration..."

    if [[ -f "$SCRIPT_DIR/local.ini" ]] && [[ ! -f "$NOTES_DIR/local.ini" ]]; then
        cp "$SCRIPT_DIR/local.ini" "$NOTES_DIR/local.ini"
        success "local.ini copied to /opt/notes/"
    elif [[ -f "$NOTES_DIR/local.ini" ]]; then
        info "local.ini already exists at /opt/notes/"
    else
        warning "local.ini not found in notes/ directory"
    fi
}

display_summary() {
    echo ""
    success "========================================"
    success "Development Setup Complete"
    success "========================================"
    echo ""
    echo "  Configuration:  $ENV_FILE"
    echo "  CouchDB User:   admin"
    echo "  CouchDB Pass:   dev_password_insecure"
    echo "  Domain:         notes.localhost"
    echo ""
    info "Next steps:"
    echo ""
    echo "  1. Start Family Budget (for nginx):"
    echo "     cd ~/familyBudget"
    echo "     docker compose --profile full up -d"
    echo ""
    echo "  2. Start Notes CouchDB:"
    echo "     cd ~/familyBudget/notes"
    echo "     docker compose -f docker-compose.notes.yml up -d"
    echo ""
    echo "  3. Access CouchDB:"
    echo "     http://notes.localhost (через nginx)"
    echo "     http://localhost:5984 (direct)"
    echo ""
    info "To add notes.localhost to /etc/hosts:"
    echo "     echo '127.0.0.1 notes.localhost' | sudo tee -a /etc/hosts"
    echo ""
}

# =============================================================================
# MAIN SETUP
# =============================================================================

main() {
    info "========================================"
    info "Notes CouchDB - Development Setup"
    info "========================================"
    echo ""

    check_docker
    setup_directories
    create_dev_env
    check_or_create_network
    copy_local_ini

    display_summary

    success "Development environment ready!"
    echo ""
}

main "$@"
