#!/bin/bash
#
# Notes CouchDB - Setup Script
#
# This script configures Notes application:
# - Creates /opt/notes/.env configuration file
# - Generates secure COUCHDB_PASSWORD
# - Prompts for NOTES_DOMAIN
#
# Usage:
#   ./setup.sh
#
# Requirements:
#   - notes/install.sh must be run first
#   - /opt/notes directory must exist
#
# Author: Family Budget Team
# Version: 1.0.0
# Date: 2025-11-16
#

set -e  # Exit on error
set -u  # Exit on undefined variable

# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOTES_DIR="/opt/notes"
ENV_FILE="$NOTES_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

print_message() {
    local color=$1
    shift
    echo -e "${color}$*${NC}"
}

info() {
    print_message "$BLUE" "[INFO] $*"
}

success() {
    print_message "$GREEN" "[SUCCESS] $*"
}

warning() {
    print_message "$YELLOW" "[WARNING] $*"
}

error() {
    print_message "$RED" "[ERROR] $*"
    exit 1
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# =============================================================================
# VALIDATION FUNCTIONS
# =============================================================================

check_notes_directory() {
    if [[ ! -d "$NOTES_DIR" ]]; then
        error "/opt/notes directory not found. Please run install.sh first:
    sudo ./install.sh"
    fi
}

check_existing_env() {
    if [[ -f "$ENV_FILE" ]]; then
        warning "Configuration file already exists: $ENV_FILE"
        echo ""
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            info "Setup cancelled. Existing configuration preserved."
            exit 0
        fi

        # Backup existing .env
        local backup_file="$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$ENV_FILE" "$backup_file"
        success "Backed up existing configuration to: $backup_file"
    fi
}

# =============================================================================
# GENERATION FUNCTIONS
# =============================================================================

generate_password() {
    local length=${1:-32}

    if command_exists openssl; then
        openssl rand -hex "$length"
    else
        # Fallback to /dev/urandom
        tr -dc 'a-f0-9' < /dev/urandom | head -c $((length * 2))
    fi
}

# =============================================================================
# CONFIGURATION FUNCTIONS
# =============================================================================

prompt_notes_domain() {
    echo ""
    info "Notes Domain Configuration"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Enter the domain for Notes access:"
    echo ""
    echo "  Development:  notes.localhost"
    echo "  Production:   notes.example.com"
    echo ""
    read -p "Notes domain [notes.localhost]: " NOTES_DOMAIN
    NOTES_DOMAIN=${NOTES_DOMAIN:-notes.localhost}

    success "Domain set to: $NOTES_DOMAIN"
}

create_env_file() {
    info "Creating configuration file: $ENV_FILE"

    # Generate secure password
    local couchdb_password
    couchdb_password=$(generate_password 32)

    # Create .env file
    cat > "$ENV_FILE" << EOF
# =============================================================================
# Notes CouchDB Environment Configuration
# =============================================================================
# Generated by notes/setup.sh at $(date +'%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to git

# =============================================================================
# CouchDB Credentials
# =============================================================================

COUCHDB_USER=admin
COUCHDB_PASSWORD=$couchdb_password

# =============================================================================
# Notes Domain Configuration
# =============================================================================

NOTES_DOMAIN=$NOTES_DOMAIN

# =============================================================================
# Data Directories
# =============================================================================

NOTES_DATA_DIR=/opt/notes/data
NOTES_BACKUP_DIR=/opt/notes/backups
NOTES_LOG_DIR=/opt/notes/logs

# =============================================================================
# Network Configuration
# =============================================================================

COUCHDB_PORT=5984
EOF

    # Set secure permissions
    chmod 600 "$ENV_FILE"

    success "Configuration file created: $ENV_FILE"
}

display_summary() {
    echo ""
    success "========================================"
    success "Notes Configuration Summary"
    success "========================================"
    echo ""
    echo "  Configuration file: $ENV_FILE"
    echo "  CouchDB user:       admin"
    echo "  CouchDB password:   [generated - 64 chars]"
    echo "  Notes domain:       $NOTES_DOMAIN"
    echo "  Data directory:     /opt/notes/data"
    echo ""
    info "IMPORTANT: Keep $ENV_FILE secure!"
    info "           This file contains sensitive credentials."
    echo ""
}

# =============================================================================
# MAIN SETUP
# =============================================================================

main() {
    info "========================================"
    info "Notes CouchDB - Setup"
    info "========================================"
    echo ""

    check_notes_directory
    check_existing_env

    prompt_notes_domain
    create_env_file
    display_summary

    success "Setup completed successfully!"
    echo ""
    info "Next steps:"
    echo "  1. Review configuration: cat $ENV_FILE"
    echo "  2. Deploy notes:         ./deploy.sh"
    echo ""
}

main "$@"
