#!/bin/bash
#
# Coturn TURN/STUN Server Setup Script
#
# Configures Coturn for P2P WebRTC support in Obsidian Self-hosted LiveSync
#
# Usage:
#   sudo bash scripts/coturn-setup.sh
#
# Requirements:
#   - Coturn installed (via install.sh)
#   - /opt/notes/.env configured (via setup.sh)
#   - Root/sudo access
#
# Author: Obsidian Sync Server Team
# Version: 1.0.0
# Date: 2025-12-30
#

set -e
set -u

# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="/opt/notes/.env"
COTURN_CONFIG="/etc/turnserver.conf"
COTURN_DEFAULT="/etc/default/coturn"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

print_message() {
    local color=$1
    shift
    echo -e "${color}$*${NC}"
}

info() {
    print_message "$BLUE" "[INFO] $*"
}

success() {
    print_message "$GREEN" "[SUCCESS] $*"
}

warning() {
    print_message "$YELLOW" "[WARNING] $*"
}

error() {
    print_message "$RED" "[ERROR] $*"
    exit 1
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (use sudo)"
    fi
}

check_coturn_installed() {
    if ! command -v turnserver >/dev/null 2>&1; then
        error "Coturn is not installed. Run install.sh first."
    fi
    success "Coturn is installed"
}

load_env_file() {
    if [[ ! -f "$ENV_FILE" ]]; then
        error ".env file not found at $ENV_FILE. Run setup.sh first."
    fi

    info "Loading configuration from $ENV_FILE..."
    # shellcheck disable=SC1090
    source "$ENV_FILE"

    # Validate required variables
    if [[ -z "${TURN_USERNAME:-}" ]] || [[ -z "${TURN_PASSWORD:-}" ]]; then
        error "TURN credentials not found in .env. Run setup.sh first."
    fi

    if [[ -z "${COTURN_EXTERNAL_IP:-}" ]]; then
        error "COTURN_EXTERNAL_IP not found in .env. Run setup.sh first."
    fi

    success "Configuration loaded"
}

generate_coturn_config() {
    info "Generating Coturn configuration..."

    cat > "$COTURN_CONFIG" << EOF
# Coturn TURN/STUN server configuration
# Auto-generated by coturn-setup.sh - DO NOT EDIT MANUALLY
# Regenerate with: sudo bash scripts/coturn-setup.sh

# Listening IP (all interfaces)
listening-ip=0.0.0.0

# External IP (VPS public IP)
external-ip=${COTURN_EXTERNAL_IP}

# STUN/TURN ports
listening-port=${COTURN_LISTENING_PORT:-3478}

# Relay ports range
min-port=49152
max-port=65535

# Realm for auth
realm=${TURN_REALM}

# Enable long-term credentials
lt-cred-mech

# User credentials (username:password)
user=${TURN_USERNAME}:${TURN_PASSWORD}

# Logging
verbose
log-file=/var/log/turnserver.log

# No TLS (we use UDP/TCP only)
no-tls
no-dtls

# No TCP relay (UDP relay only for better performance)
no-tcp-relay

# Fingerprint for WebRTC
fingerprint

# Use real client IP from X-Forwarded-For (if behind proxy)
# Disabled by default for security
# user-quota=0
# total-quota=0

# Deny private IP ranges from being relayed
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255

# Allow loopback
allowed-peer-ip=127.0.0.1

EOF

    success "Coturn configuration generated at $COTURN_CONFIG"
}

enable_coturn_service() {
    info "Enabling Coturn service..."

    # Enable in /etc/default/coturn
    if grep -q "^#TURNSERVER_ENABLED=1" "$COTURN_DEFAULT" 2>/dev/null; then
        sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' "$COTURN_DEFAULT"
    elif ! grep -q "^TURNSERVER_ENABLED=1" "$COTURN_DEFAULT" 2>/dev/null; then
        echo "TURNSERVER_ENABLED=1" >> "$COTURN_DEFAULT"
    fi

    success "Coturn service enabled"
}

restart_coturn() {
    info "Restarting Coturn service..."

    systemctl daemon-reload
    systemctl restart coturn
    sleep 2

    if systemctl is-active --quiet coturn; then
        success "Coturn service is running"
    else
        error "Coturn service failed to start. Check: sudo journalctl -u coturn -n 50"
    fi
}

display_summary() {
    echo ""
    success "========================================"
    success "Coturn TURN/STUN Server Setup Complete!"
    success "========================================"
    echo ""

    info "Configuration Summary:"
    echo "  External IP:   $COTURN_EXTERNAL_IP"
    echo "  Listening Port: ${COTURN_LISTENING_PORT:-3478}"
    echo "  Relay Ports:   49152-65535"
    echo "  Username:      $TURN_USERNAME"
    echo "  Password:      ${TURN_PASSWORD:0:8}... (hidden)"
    echo "  Realm:         $TURN_REALM"
    echo ""

    info "Client Configuration (Obsidian):"
    echo "  STUN Server:   stun:stun.l.google.com:19302"
    echo "  TURN Server:   turn:${COTURN_EXTERNAL_IP}:${COTURN_LISTENING_PORT:-3478}"
    echo "  TURN Username: $TURN_USERNAME"
    echo "  TURN Password: $TURN_PASSWORD"
    echo ""

    info "Service Status:"
    systemctl status coturn --no-pager | head -10
    echo ""

    info "Logs:"
    echo "  sudo journalctl -u coturn -f"
    echo "  sudo tail -f /var/log/turnserver.log"
    echo ""
}

# =============================================================================
# MAIN SETUP
# =============================================================================

main() {
    info "========================================"
    info "Coturn TURN/STUN Server Setup"
    info "========================================"
    echo ""

    check_root
    check_coturn_installed
    load_env_file

    echo ""
    generate_coturn_config
    enable_coturn_service
    restart_coturn

    echo ""
    display_summary
}

# Execute main only when script is run directly (not when sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
