#!/bin/bash
#
# Generate vault connection parameters documentation
# Reads .env and creates docs/VAULT-PARAMETERS.md
#

set -e
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="/opt/notes/.env"
OUTPUT_FILE="$PROJECT_ROOT/docs/VAULT-PARAMETERS.md"

# Source .env to get variables
if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE not found."
    echo "Run setup.sh first to generate configuration."
    exit 1
fi

source "$ENV_FILE"

# Get current date
CURRENT_DATE=$(date +"%Y-%m-%d")

# Create documentation
cat > "$OUTPUT_FILE" << EOF
# P2P Vault Connection Parameters

**Auto-generated on:** $CURRENT_DATE

This document contains connection parameters for all configured P2P vaults.
Use these parameters to configure Obsidian Self-hosted LiveSync plugin on your devices.

---

## Relay Server (Shared)

All vaults use the same Nostr Relay for WebSocket signaling:

\`\`\`
Relay URL: ${SERVERPEER_RELAYS}
\`\`\`

**Important:** This URL must be identical on all devices for all vaults.

---

EOF

# Check if VAULT_COUNT is set
VAULT_COUNT=${VAULT_COUNT:-1}

# Generate parameters for each vault
for ((i=1; i<=VAULT_COUNT; i++)); do
    vault_name_var="VAULT_${i}_NAME"
    vault_roomid_var="VAULT_${i}_ROOMID"
    vault_passphrase_var="VAULT_${i}_PASSPHRASE"
    vault_container_var="VAULT_${i}_CONTAINER"

    vault_name="${!vault_name_var:-Vault$i}"
    vault_roomid="${!vault_roomid_var}"
    vault_passphrase="${!vault_passphrase_var}"
    vault_container="${!vault_container_var}"

    cat >> "$OUTPUT_FILE" << EOF
## Vault #$i: $vault_name

### Obsidian Configuration

Configure these settings in Obsidian:

\`\`\`
Settings → Self-hosted LiveSync → P2P Configuration

Enabled:             ✓
Relay URL:           ${SERVERPEER_RELAYS}
Group ID:            $vault_roomid
Passphrase:          $vault_passphrase
Device Peer ID:      [unique for each device, e.g., laptop-work, phone-personal]
Auto Start P2P:      ✓
Auto Broadcast:      ✓
\`\`\`

### Setup on Each Device

**Device 1 (e.g., Laptop):**
\`\`\`
Relay URL:       ${SERVERPEER_RELAYS}
Group ID:        $vault_roomid
Passphrase:      $vault_passphrase
Device Peer ID:  laptop-${vault_name,,}
\`\`\`

**Device 2 (e.g., Phone):**
\`\`\`
Relay URL:       ${SERVERPEER_RELAYS}
Group ID:        $vault_roomid
Passphrase:      $vault_passphrase
Device Peer ID:  phone-${vault_name,,}
\`\`\`

**Device 3 (e.g., Tablet):**
\`\`\`
Relay URL:       ${SERVERPEER_RELAYS}
Group ID:        $vault_roomid
Passphrase:      $vault_passphrase
Device Peer ID:  tablet-${vault_name,,}
\`\`\`

### Server Information

\`\`\`
ServerPeer Container: $vault_container
Status:               docker ps | grep $vault_container
Logs:                 docker logs $vault_container
\`\`\`

---

EOF
done

# Add security notes
cat >> "$OUTPUT_FILE" << 'EOF'
## Security Notes

**⚠️ KEEP THESE PARAMETERS SECRET:**

- Group ID and Passphrase are used for authentication and encryption
- Do not share these parameters publicly
- Store them securely in a password manager
- Each vault has unique Group ID and Passphrase
- Relay URL can be shared (it's the server address)

**Backup:**
Save this file in a secure location (password manager, encrypted backup).

---

## Troubleshooting

### Connection Issues

**Devices can't see each other:**
1. Verify Relay URL is correct on all devices
2. Check that Group ID matches exactly
3. Ensure Passphrase matches exactly
4. Verify ServerPeer container is running:
   \`\`\`bash
   ssh ikenibornsync "docker ps | grep serverpeer"
   \`\`\`

**ServerPeer not responding:**
\`\`\`bash
# Check all ServerPeer containers
ssh ikenibornsync "docker ps --filter 'name=serverpeer'"

# View logs for specific vault
ssh ikenibornsync "docker logs notes-serverpeer-VAULTNAME --tail 50"

# Restart if needed
ssh ikenibornsync "docker restart notes-serverpeer-VAULTNAME"
\`\`\`

### Check Nostr Relay

\`\`\`bash
# View Nostr Relay logs (shared by all vaults)
ssh ikenibornsync "docker logs notes-nostr-relay --tail 50"

# Should see WebSocket connections from devices
[INFO] new client connection (cid: xxx, ip: "x.x.x.x")
[INFO] origin: "app://obsidian.md"
\`\`\`

---

**Last updated:** $CURRENT_DATE
**Generated by:** scripts/generate-vault-docs.sh
EOF

echo "✓ Generated: $OUTPUT_FILE"
echo "  Vault count: $VAULT_COUNT"
